### ISSUE TITLE
when doing batch I am supposed to do dir/*.ext correct?

### ISSUE THREAD

**Issue by CoffeeIsLife87** [lucienmaloney/BeatSaber.jl#1]
I cant do batch 
it just spits out a bunch of errors
I am able to do single songs tho

**Comment by lucienmaloney** [comment]
Ah, are you on Windows? I might not have set up wildcard behavior correctly
there. I'll make a note of that and fix it, thanks.

**Comment by CoffeeIsLife87** [comment]
yeah I am on windows

**Comment by lucienmaloney** [comment]
Alright, it should be working now.
