### ISSUE TITLE
massive drop in audio quality after mapping

### ISSUE THREAD

**Issue by CoffeeIsLife87** [lucienmaloney/BeatSaber.jl#10]
comparing the ogg to source file it sounds considerably worse
can you make a way for us to either use our own bitrate or add a --argument for max quality audio

**Comment by lucienmaloney** [comment]
Ah, the audiophiles have come for me. I knew it was only a matter of time.

But in all seriousness, I can't tell the difference in quality after running two ffmpeg commands with different bitrates. So I'm not sure if this is worth adding in a flag for, but maybe... I'll sleep on it, and leave the issue open until I make a decision

**Comment by lucienmaloney** [comment]
After thinking it over, I think this is too niche to warrant a flag. I want to keep the utility as simple as possible and avoid flags if at all possible. Anyone who really wants to have absolute control over the audio can always manually edit in a `-b:audio 192k` or whatever number to the ffmpeg command, but I think for most people it's a non-issue.
