### ISSUE TITLE
ERROR: LoadError: UndefVarError: rawname not defined

### ISSUE THREAD

**Issue by Tutlek** [lucienmaloney/BeatSaber.jl#2]
![hghghded](https://user-images.githubusercontent.com/61251083/76562974-c6bf5c80-64a6-11ea-9196-b681406fd2d6.jpg)

Not sure whats wrong,could use your help :)
Ty

**Comment by lucienmaloney** [comment]
Oops, that's my bad. Thanks for letting me know. Should be fixed now
