### ISSUE TITLE
I cant play the songs I had it map

### ISSUE THREAD

**Issue by CoffeeIsLife87** [lucienmaloney/BeatSaber.jl#7]
I used spotdl python tool to take some songs off of spotify and I ran them through the map tool but when I got into beat saber and clicked on them there was no music
I open the song (in beat saber) and I get a black screen followed by the song completion menu with a score of 0

**Comment by lucienmaloney** [comment]
Can you share a zip file with the songs you tried to map as well as a zip of the map folders generated?

**Comment by CoffeeIsLife87** [comment]
https://drive.google.com/file/d/1DJS_UPZ0di2WD-sQ_AccWWPk2gNT6Gfl/view?usp=sharing
the file was to big to upload to github

**Comment by lucienmaloney** [comment]
Hm, seems like Beat Saber reacts poorly to metadata in songs. I wonder why that is. In any case, I updated the code to strip it out so it shouldn't matter now.

Can you pull the new changes and try remapping the songs to see if they work on your end now?

**Comment by CoffeeIsLife87** [comment]
sure

**Comment by CoffeeIsLife87** [comment]
that fixed it
