### ISSUE TITLE
the beat of the songs does not match up with the blocks

### ISSUE THREAD

**Issue by CoffeeIsLife87** [lucienmaloney/BeatSaber.jl#8]
title
same maps I sent before (those worked by the way. Good job!)
https://drive.google.com/file/d/1H5-PGoSUuUTn5o-Lp9s-Kn6WRYKvcVrc/view?usp=sharing example

**Comment by lucienmaloney** [comment]
Just finished playing through the songs. Aside from some issues mapping silence, they seem... decently well aligned. You're right that there's definitely room for improvement, though. It's the next thing I intend to work on, but it's a tricky problem.

Each song essentially creates its own miniature [cocktail party problem](https://en.wikipedia.org/wiki/Cocktail_party_effect). While it's easy enough for a human to tune into a particular instrument or rhythm to map, the algorithm picks up on all sorts of distractions, which can make things a bit funky. Right now, the less complex the song, the better the note placement. 8-bit music, for example, gets timed almost perfectly. This isn't to say that things can't be improved, just that progress might be slow and incremental: no panacea here. So keep posted for updates and I'll try my best to steadily improve that side of things.

**Comment by lucienmaloney** [comment]
Okay, I've made some improvements to note placement. There's still progress to be made, but I think it matches up a bit better now. You can try remapping those same songs if you want to compare.

**Comment by lucienmaloney** [comment]
Made some more improvements. Still not perfect, but it never will be, so I think this is as good a point as any to close the issue.
